- name: put named.conf.local
  template: src=named.conf.local dest={{ ext_bind_conf_volume }}/named.conf.local

- name: start a bind container
  docker:
    image: gitinsky/bind:0.1.1
    state: started
    read_only: yes
    hostname: "{{ ansible_hostname }}-bind"
    ports:
      - "{{ ansible_default_ipv4.address }}:53:53"
      - "{{ ansible_default_ipv4.address }}:53:53/udp"
    restart_policy: always
    restart_policy_retry: 10000000
    volumes:
      - "{{ ext_bind_conf_volume }}/named.conf.local:/etc/bind/named.conf.local"
      - "{{ ext_bind_slave_zones_volume }}:/etc/bind/zones/slave"
      - "{{ ext_bind_var_run_volume }}:/var/run/named"
      - "{{ ext_bind_var_cache_volume }}:/var/cache/bind"
